# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Asset(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, asset: str=None):  # noqa: E501
        """Asset - a model defined in Swagger

        :param asset: The asset of this Asset.  # noqa: E501
        :type asset: str
        """
        self.swagger_types = {
            'asset': str
        }

        self.attribute_map = {
            'asset': 'asset'
        }
        self._asset = asset

    @classmethod
    def from_dict(cls, dikt) -> 'Asset':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Asset of this Asset.  # noqa: E501
        :rtype: Asset
        """
        return util.deserialize_model(dikt, cls)

    @property
    def asset(self) -> str:
        """Gets the asset of this Asset.


        :return: The asset of this Asset.
        :rtype: str
        """
        return self._asset

    @asset.setter
    def asset(self, asset: str):
        """Sets the asset of this Asset.


        :param asset: The asset of this Asset.
        :type asset: str
        """

        self._asset = asset
