# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ConstantValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, value: float = None):  # noqa: E501
        """ConstantValue - a model defined in Swagger

        :param value: The value of this ConstantValue.  # noqa: E501
        :type value: float
        """
        self.swagger_types = {"value": float}

        self.attribute_map = {"value": "value"}
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> "ConstantValue":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConstantValue of this ConstantValue.  # noqa: E501
        :rtype: ConstantValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> float:
        """Gets the value of this ConstantValue.


        :return: The value of this ConstantValue.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this ConstantValue.


        :param value: The value of this ConstantValue.
        :type value: float
        """

        self._value = value
